export const SET_QUIZ_QUESTIONS = 'SET_QUIZ_QUESTIONS';
export const INCREMENT_RIGHT_ANSWERS = 'INCREMENT_RIGHT_ANSWERS';
export const UPDATE_CURRENT_QUESTION = 'UPDATE_CURRENT_QUESTION';
export const MARK_CATEGORY_SELECTED = 'MARK_CATEGORY_SELECTED';
export const RESET_GAME = 'RESET_GAME';